project:
  type: book

book:
  title: "Autonomous and Adaptive Systems"
  author: "Alessia Crimaldi"
  date: "2/28/2025"
  chapters:
    - index.qmd
    - sec1.qmd
    - sec2.qmd
    - sec3.qmd
    - sec4.qmd
    - sec5.qmd
    - sec6.qmd
    - sec7.qmd
    - sec8.qmd
    - sec9.qmd
    - sec10.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
